
package gov.iti.jets.services.atm;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * Eclipse Metro/4.0.2 (RELEASE-4.0.2-ffda8c0; 2023-01-31T10:50:38+0000) XMLWS-Impl/4.0.1 XMLWS-API/4.0.0 XMLB-Impl/4.0.2 XMLB-API/4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "Atm", targetNamespace = "http://services.day1.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Atm {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "login", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.Login")
    @ResponseWrapper(localName = "loginResponse", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.LoginResponse")
    @Action(input = "http://services.day1.example.com/Atm/loginRequest", output = "http://services.day1.example.com/Atm/loginResponse")
    public String login(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Withdraw")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Withdraw", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.Withdraw")
    @ResponseWrapper(localName = "WithdrawResponse", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.WithdrawResponse")
    @Action(input = "http://services.day1.example.com/Atm/WithdrawRequest", output = "http://services.day1.example.com/Atm/WithdrawResponse")
    public double withdraw(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

    /**
     * 
     * @return
     *     returns double
     */
    @WebMethod(operationName = "ViewBalance")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ViewBalance", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.ViewBalance")
    @ResponseWrapper(localName = "ViewBalanceResponse", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.ViewBalanceResponse")
    @Action(input = "http://services.day1.example.com/Atm/ViewBalanceRequest", output = "http://services.day1.example.com/Atm/ViewBalanceResponse")
    public double viewBalance();

    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod(operationName = "Deposite")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "Deposite", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.Deposite")
    @ResponseWrapper(localName = "DepositeResponse", targetNamespace = "http://services.day1.example.com/", className = "gov.iti.jets.services.atm.DepositeResponse")
    @Action(input = "http://services.day1.example.com/Atm/DepositeRequest", output = "http://services.day1.example.com/Atm/DepositeResponse")
    public double deposite(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0);

}
