
package gov.iti.jets.services.atm;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * Eclipse Metro/4.0.2 (RELEASE-4.0.2-ffda8c0; 2023-01-31T10:50:38+0000) XMLWS-Impl/4.0.1 XMLWS-API/4.0.0 XMLB-Impl/4.0.2 XMLB-API/4.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AtmService", targetNamespace = "http://services.day1.example.com/", wsdlLocation = "http://localhost:9090/jax-wss/ws/atmservices?wsdl")
public class AtmService
    extends Service
{

    private static final URL ATMSERVICE_WSDL_LOCATION;
    private static final WebServiceException ATMSERVICE_EXCEPTION;
    private static final QName ATMSERVICE_QNAME = new QName("http://services.day1.example.com/", "AtmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/jax-wss/ws/atmservices?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ATMSERVICE_WSDL_LOCATION = url;
        ATMSERVICE_EXCEPTION = e;
    }

    public AtmService() {
        super(__getWsdlLocation(), ATMSERVICE_QNAME);
    }

    public AtmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ATMSERVICE_QNAME, features);
    }

    public AtmService(URL wsdlLocation) {
        super(wsdlLocation, ATMSERVICE_QNAME);
    }

    public AtmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ATMSERVICE_QNAME, features);
    }

    public AtmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AtmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Atm
     */
    @WebEndpoint(name = "AtmPort")
    public Atm getAtmPort() {
        return super.getPort(new QName("http://services.day1.example.com/", "AtmPort"), Atm.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Atm
     */
    @WebEndpoint(name = "AtmPort")
    public Atm getAtmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.day1.example.com/", "AtmPort"), Atm.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ATMSERVICE_EXCEPTION!= null) {
            throw ATMSERVICE_EXCEPTION;
        }
        return ATMSERVICE_WSDL_LOCATION;
    }

}
